server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:foodrush_auth}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog-master.xml

jwt:
  secret: foodrush-secret-key-2026
  expiration: 86400000

cors:
  allowed-origins: http://localhost:4200
